---

wallets:
  - wallet: Lunc Original
    seed: YDS8n7I9GsZziVd8MeH1lYy0o4inRji8mnoOT6k3JnFVet+UnI2iI73Ri3MaqdNEJpFz58W5F3Gno1tayaVCJANm74ug+zFXQT3yXHnYe562x9fbd/k5LVBo39uNS3biyq4bnfJIwIQlEXbT3kTHE62XEZNmEF69qxsLPe2RKKW8ZwP4TKQm6B6P9h/Zj8vUawOrczJsf3N3lfOx2BqlYQ==*3GzzOaq6Fc/C6oKcqRGoeQ==*Yr58gPsbU9TuqgFeFybMTA==*cJkIeEDhQq3Ok0aR7kI7VQ==
    address: terra1n6r99pjv4zpzeuralcy7uh7ygll3zjkcnkj25e
    delegations:
      threshold: 1000
      redelegate: 100%

  - wallet: Lunc Longterm
    seed: GboTYWLKjQKdKvk5DbSPapo9P32UXCkf/YHy6apcxcR6MK3t+2raAt4vpz6+J3aFECO+9m76yV/fpqEfjH0nNYQYE3oouXP0+PlOAiBuNPj61z0neIRjEFbjbmCQIWLZf0ws1pLf2gnGBHbWSjRwyA4336X+W772/bN+BxiXxIqRahiATTS5i1LOVpqZRTWZwTM1TcF1waEjJWCHaMwp*p6zqBptMqy451snpnz3KHQ==*DBh/DiXDcWuSn2UZNqrFEg==*K0BSC/Npl9jNta00tbUqbw==
    address: terra1yylkeekjny0yvlry3mfmj7xh38phvcq5fl7hd0
    delegations:
      threshold: 1000
      redelegate: 100%

  - wallet: Lunc Batch 3
    seed: 0iu82eSTefaLOjpQK7AybE5mUV/bKWfBYoDbu0coO9R6mNrDPqRsw7A19f89DST7/Nwy0QjCyV4pBWDw8W7ATgrDVCOufs8sFP4A1deqqmIOiC78oWAG9rmGG4SrYr6mp2TiK0G3BmoXLUqzn/HvcUKomwJZuUtZEm6P9VFAWLSF2u2YYAwijieeNH5wAGHVrr0G3kFh4IaF0fy+LIY=*xmQ7gbGzMXfE/cbLfiMEDw==*tl85F4fGblRZm/sY49Hbwg==*gEpHQbGOfnCxE8jwDTwEsw==
    address: terra1rz42apzse9979r6zt7h5fgm7ratpk9vjhzmkad
    delegations:
      threshold: 1000
      redelegate: 100%

  - wallet: Lunc last batch
    seed: nkk+QLZnoEi+zwgOOuWWTLJpbnQCqx6RLD6djzfcEe4WOaHxUT0GeZglzV5SocEBDQ+NysVCOa4GYeNgW9orOUj8CeddI/r7lbKoAbPycjRGkLeMvRAxzezXZqGlmTwAesDhSLjb1IAK4qJK4qBufYugV8mkxxIOSbm4PdqModWbLUabNWY6pTAtZwFTtwJMRAHbt8E=*yuhuRwQtzOk1b2oy02mzzA==*CGeWDHAa5hZPG/p/5PRAyg==*LSYtI663RUHY9yAIszRwTQ==
    address: terra1atwwg2x8v553gj7wutsvqpuwh2njnvyesp03s7
    delegations:
      threshold: 1000
      redelegate: 100%

  - wallet: Lunc 20 Million
    seed: mqBj1QhkUM6JoMhMrUnrr8/wbXpjYhyiTRsAbEfZTiX4oJ44m5s35KvHjMA6ZJB09OSX0w6Z9JfV4KgJJ/KOaSjpNdwoYGxhpGLwfW6r1vL85Ya9IQcpNelgNSf1LA6fmqj+LeurCU30yr7r798aktB0cs5UiaFzCG8N3IufG31dpfN3oM6cQWozX9yl++49D9bd/U+Uvw==*228TAx6LeD1kTXHNGBxaDw==*/Q5ROIuc9vxZEmCoN3pFvQ==*4udsDN3K6p/PEJmaVOlBJA==
    address: terra1adfylse87rxmuh95592n99zdne4rudzwxucl35
    delegations:
      threshold: 1000
      redelegate: 100%

  - wallet: Onyx
    seed: KJqpiASRwdmo9msEEu7XR7SeE21+7dkjkAgxZm0wVD866VIsKK1dLqS9WujoKnyGXva9tCyPq5/rOaZDsEAypDkhNnVJfB5JDRUM3J3mGldZo4Qzuk9wQgc+gdsVvm+kj+siBKhgBPYZCNmayGkQPrx9n3j0jdrgiTWYb+G9YiknvE/9qtygnqrbfbMHLd6CFBuMkto=*yeHYUlCuF6lYdlqiTywg1g==*nFU+VtIb5PeukKcBmnGsVw==*LOQVECqFcqCdYYjx6tSpmQ==
    address: terra1kgge7tyctna52qfskpkw73xu4fhmd0y29ravr6
    delegations:
      redelegate: 100%

  - wallet: Toxiclabs
    seed: 5QSZF6zRBYyzt65+Gw3ksV9FDVYUAYF2lcLPq8ZDd/j9qppuhP4K6jwJ/ANdZDLwyPkXt8kZZ8oHdFyS3QdH76LSWylwuXUhIRXVq+oa93U06aactRWP7OXsmmWU3jP0MH5t0R+W7YngaG4olvZ0mFMtUzdD2rt6PZBQvuQwyFDIAmzLwu7R6qe1vT9sD9oUDnG/dpAKijY=*lKjAD6TVu+NfNbyf0YtD9g==*G2ka7OPoxsmIJ1lG2DFfzQ==*PkT9uYFX/9nfWaTohU33xg==
    address: terra15rfpfwj7xklq3ddwl7dymfc04xp3atr4rtnads
    delegations:
      redelegate: 100%

...