---

wallets:

  # - wallet: lunc original
  #   seed: ALEWuiteA9oIEPgcSuurGGqe4zy2e1KuNq3aTxrxEMzUntxzx1yPI78Th1Y8FxCMRd/Y7Ew/tQhZ8nn1YOZYbmCkIykYq7vDSn+UuMOmRQvPjKQqzXE5vfOqIwV1WwbgDPFnhRVzR5kbzgnqYEtzOWwgmOu99Wj3qLNk/EUtcOnettY/USbwmU1InkODv3+/VAqHfHg45cNjqqW26NBYzw==*sXk+YJbENIEIC2/jdbUBFQ==*NhzCgPZXfyAGS0GpIA/5zA==*hkoJloGOu+qGRreLqnpyCg==
  #   address: terra1n6r99pjv4zpzeuralcy7uh7ygll3zjkcnkj25e
  #   delegations:
  #     threshold: 500
  #     redelegate: 100%

  # - wallet: lunc longterm
  #   seed: HcNW9e0qY4JS/0U2XrqPV46sWF2rfB1UCCMHKxo3ZhF7nDx0jXj23H5u1TMWmdQXE8SacAGEnVo3pb87IS2lBIS88GsDUssbiYD65gKhoDHXdvTkqt+RQbDOEr51lgae9i8JuXQIpf4lwEPKjuIT4E637hbF1nWymSpvycbIu23dYXUE7KvkIxW1TSW7QtBqtQ9zsISuOWYyPZVX9swL*ttnRDtJnfY/nhamTRImvKQ==*kpuPPLQi2GMqFuqPlV3x1w==*mTFQSjthhKx8+ciMQe1kGA==
  #   address: terra1yylkeekjny0yvlry3mfmj7xh38phvcq5fl7hd0
  #   delegations:
  #     redelegate: 100%

  # - wallet: lunc batch3
  #   seed: XgvCYHpiDX9K9G0Pi3H0oLKb8bboU1Cn/ycONiaZjj14wHR/xX2GhrvlDOJ0aggVwJ0C4ul+0ql46g/c3KpQCe8eCWRRmmm4agsd2XGsKldK1CZ1XNEagxjVRoCJYBk9vNNB/Z95qt0qPDENJDWIJzos+6EiHn+SC1rTr1C1p5vFoBsLEllo3uyNtevuGJNls96yR2tJIpH2rj8Kcuw=*YpqBZhko8kqKUb1P4USV+Q==*Qx4SKqs0SsMS6ntdrJPrtg==*AXyZ8FW1YtQgdZqhNJpSXQ==
  #   address: terra1rz42apzse9979r6zt7h5fgm7ratpk9vjhzmkad
  #   delegations:
  #     redelegate: 100%

  # - wallet: lunc last batch
  #   seed: UR6eNG4SpIw6gO2y/4jDnAMGS4nCFsIR30GIYdZTFkkJpzbHqL67Ip+GSblvLbBs+6LEMkcGi8J63Z1f0U0/CGo5w0CeyLPp6u4LdphdxtHUn4bbytuo9Xw46n8UCwiiMzw2VfrVKuSmkYNXNPz8HuYkpas9UKdHZJAZG4xdn8NCPQVy4TMXxLa/MDtyu1Be09Orgfc=*72U8+w8QDksT+8U7gsf+tA==*aMmmgg85xQqhd1sl1vJ3qw==*LMyd0J0WdMut5ecuGhhiLw==
  #   address: terra1atwwg2x8v553gj7wutsvqpuwh2njnvyesp03s7
  #   delegations:
  #     redelegate: 100%

  # - wallet: lunc 20 million
  #   seed: uk2z0GkKqb7X3I7NrHsC44kwZVM4JgoYBriJ4yyP7Lr+uaiCjGKDGpgD0ACc4ODZJznHBRXexm689Q8IMYLuLkUM6+5QkiTYXju6JzhGTXWg+VC23gmBfH8y8NH74oi/wIhp/eQ0pXPN2llg16bRf5HueD6JgVf1E85suqU7hS6BB/onaJezTTr8xzAWeuixoGWmE4d3Gw==*WJZTdUK1/HX2wgsHuZCJiQ==*MHkkQ5y5PS3zfoSshbq+VQ==*s74ny4h6o8AqWOjoTzUk6g==
  #   address: terra1adfylse87rxmuh95592n99zdne4rudzwxucl35
  #   delegations:
  #     redelegate: 100%

  - wallet: onyx
    seed: +eiwSy6Pvb6eDoPy7Ul5Phwo/aCTKTR33zFyIWhb63H3wNpBYfQQElfH7T+yep/GAsg4nWuZ6ns+bu8MBaKmWPr0F0sI79LvG4c+Et/oQcYI2mPNN6m8+fOx7sjQBLZFTDr9r9/wmVShL6+c6t8NyQBW7gS+K0+eGmwEC9HjhKhvmE1tc2eNBtPvueMbkBA8xvzST7s=*uY/ACwhw57w8qVjNxYbGqw==*RI8ZOf8R3qkw50etQJaAOw==*Nv5jh500jLlDWa3nCO12Uw==
    address: terra1kgge7tyctna52qfskpkw73xu4fhmd0y29ravr6
    delegations:
      redelegate: 100%

  - wallet: toxiclabs
    seed: kkJVRrD09UDJZPQv0sfglRzN9eLSzeHGDfqcmCw3zNvEnBRkfmyMVCi5oeZYSjEkbZ60guMxffDvUqcF5GHjJc2do7MD08x1DQczNXJwQF93MBbWYQJGKulTQOMhqJH3Q2hLTL0rdtZwOioaxIBSYntQCWBSGrlTv9RXxyNF6GSpMlRmNjn6z9SHm1RAmikYh66VdsJFfR4=*fbW/vU2VngTUekWddpEmVg==*lNfuLhhFQnaowBObMYAtkw==*ZylH2y6sBJKorluwcAZ1EA==
    address: terra15rfpfwj7xklq3ddwl7dymfc04xp3atr4rtnads
    delegations:
      threshold: 100
      redelegate: 100%


